// src/actions/types.js

// Auth Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// Student Types
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';

// Library Types
export const FETCH_OVERDUE_BOOKS = 'FETCH_OVERDUE_BOOKS';
export const FETCH_OVERDUE_BOOKS_SUCCESS = 'FETCH_OVERDUE_BOOKS_SUCCESS';
export const FETCH_OVERDUE_BOOKS_FAILURE = 'FETCH_OVERDUE_BOOKS_FAILURE';
export const ADD_BORROW_RECORD = 'ADD_BORROW_RECORD';
export const UPDATE_BORROW_RECORD = 'UPDATE_BORROW_RECORD';
export const DELETE_BORROW_RECORD = 'DELETE_BORROW_RECORD';

// Fee Types
export const FETCH_UNPAID_FEES = 'FETCH_UNPAID_FEES';
export const FETCH_UNPAID_FEES_SUCCESS = 'FETCH_UNPAID_FEES_SUCCESS';
export const FETCH_UNPAID_FEES_FAILURE = 'FETCH_UNPAID_FEES_FAILURE';
export const ADD_FEE_RECORD = 'ADD_FEE_RECORD';
export const UPDATE_FEE_RECORD = 'UPDATE_FEE_RECORD';
export const DELETE_FEE_RECORD = 'DELETE_FEE_RECORD';
export const GET_FEES = 'GET_FEES';
export const ADD_FEE = 'ADD_FEE';
export const FEES_ERROR = 'FEES_ERROR';
export const GET_STUDENTS = 'GET_STUDENTS';
export const LIBRARY_STATUS_ERROR ='LIBRARY_STATUS_ERROR'
